### ISSUE TITLE
Doesnt work (at least not on 1.21)

### ISSUE THREAD

**Issue by appztr4ckt** [Fusezion/skript-advancements#1]
I recently installed the Skript Addon "skript-advancements" on my Paper 1.21 server. While the installation process did not throw any errors in the console, the addon does not seem to function properly. It is not listed under `/skript info`, and any scripts utilizing the addon’s syntaxes do not work.

**Comment by Fusezion** [comment]
HI! Sorry however at this moment in time I am not attached to the skript-advancements addon, the one you would/should be using doesn't seem to have any links to support, I have gone ahead and contacted the existing maintainer, I'll keep this opened until he responds.

**Comment by Fusezion** [comment]
Based off his response, he seems to be more preoccupied with the rewrite and is not expecting to be doing any updates for the time being.
